/**
 * Global application state
 */

export const state = {
  character: null,
  fileHandle: null,
  sourceHandle: null,
  recentDirectories: [],
  liveSync: false,
  saveTimer: null,
  dirty: false,
  activeImagePath: null,
  imageManifest: [],
  imageObjectUrls: [],
  lightboxOpen: false,
  tocCollapsed: false,
  tocOverlayOpen: false,
  theme: "dark",
};

/**
 * DOM element references
 */
export const elements = {
  syncPill: document.getElementById("sync-pill"),
  syncLabel: document.getElementById("sync-label"),
  setupScreen: document.getElementById("setup-screen"),
  setupRecent: document.getElementById("setup-recent"),
  setupRecentList: document.getElementById("setup-recent-list"),
  setupRecentEmpty: document.getElementById("setup-recent-empty"),
  hero: document.getElementById("hero"),
  layout: document.getElementById("layout"),
  portraitImage: document.getElementById("portrait-image"),
  portraitCaption: document.getElementById("portrait-caption"),
  portraitCounter: document.getElementById("portrait-counter"),
  portraitPrev: document.getElementById("portrait-prev"),
  portraitNext: document.getElementById("portrait-next"),
  lightbox: document.getElementById("lightbox"),
  lightboxImage: document.getElementById("lightbox-image"),
  lightboxCaption: document.getElementById("lightbox-caption"),
  lightboxClose: document.getElementById("lightbox-close"),
  lightboxPrev: document.getElementById("lightbox-prev"),
  lightboxNext: document.getElementById("lightbox-next"),
  characterName: document.getElementById("character-name"),
  characterSummary: document.getElementById("character-summary"),
  identityGrid: document.getElementById("identity-grid"),
  baseStats: document.getElementById("base-stats"),
  buildPriorities: document.getElementById("build-priorities"),
  abilitiesTable: document.getElementById("abilities-table"),
  savesTable: document.getElementById("saves-table"),
  skillsTable: document.getElementById("skills-table"),
  attacksTable: document.getElementById("attacks-table"),
  combatLevelNotes: document.getElementById("combat-level-notes"),
  spellcastingSummary: document.getElementById("spellcasting-summary"),
  spellSections: document.getElementById("spell-sections"),
  proficienciesList: document.getElementById("proficiencies-list"),
  featuresList: document.getElementById("features-list"),
  levelChecklist: document.getElementById("level-checklist"),
  inventoryTable: document.getElementById("inventory-table"),
  inventoryNotesList: document.getElementById("inventory-notes-list"),
  languagesRow: document.getElementById("languages-row"),
  raceNotes: document.getElementById("race-notes"),
  backgroundFeature: document.getElementById("background-feature"),
  roleplayList: document.getElementById("roleplay-list"),
  appearanceList: document.getElementById("appearance-list"),
  storyParagraphs: document.getElementById("story-paragraphs"),
  unfilledList: document.getElementById("unfilled-list"),
  notesReminders: document.getElementById("notes-reminders"),
  tableReminders: document.getElementById("table-reminders"),
  hpSummary: document.getElementById("hp-summary"),
  hpFill: document.getElementById("hp-fill"),
  sessionBars: document.getElementById("session-bars"),
  sessionCoins: document.getElementById("session-coins"),
  sourceData: document.getElementById("source-data"),
  currentHp: document.getElementById("currentHp"),
  tempHp: document.getElementById("tempHp"),
  arrows: document.getElementById("arrows"),
  slotFields: document.getElementById("slot-fields"),
  gold: document.getElementById("gold"),
  silver: document.getElementById("silver"),
  copper: document.getElementById("copper"),
  inventoryNotes: document.getElementById("inventoryNotes"),
  tocList: document.getElementById("toc-list"),
  tocSidebar: document.getElementById("toc-sidebar"),
  tocOpenBtn: document.getElementById("toc-open-btn"),
  themeToggleBtn: document.getElementById("theme-toggle-btn"),
  tocDockBtn: document.getElementById("toc-dock-btn"),
  tocCloseBtn: document.getElementById("toc-close-btn"),
  tocOverlayBackdrop: document.getElementById("toc-overlay-backdrop"),
};
