#!/usr/bin/env bash
#
# Configure Android *release* signing for the freshly-scaffolded Gradle project.
#
# `src-tauri/gen/android` is gitignored and regenerated by `tauri android init` on every CI
# run (see src-tauri/.gitignore), so the signing config can't live in the repo — we inject it
# here from four GitHub Actions secrets. With no secrets present the script exits non-zero so a
# release build fails loudly instead of silently shipping an unsigned / debug-signed APK.
#
# Required env (set as repo secrets, passed through in release.yml):
#   ANDROID_KEYSTORE_BASE64    base64 of the release keystore (.jks)
#   ANDROID_KEYSTORE_PASSWORD  keystore (store) password
#   ANDROID_KEY_ALIAS          key alias inside the keystore
#   ANDROID_KEY_PASSWORD       password for that alias
#
# Run from the repo root, after `tauri android init`.
set -euo pipefail

: "${ANDROID_KEYSTORE_BASE64:?ANDROID_KEYSTORE_BASE64 is not set — add it as a repo secret}"
: "${ANDROID_KEYSTORE_PASSWORD:?ANDROID_KEYSTORE_PASSWORD is not set — add it as a repo secret}"
: "${ANDROID_KEY_ALIAS:?ANDROID_KEY_ALIAS is not set — add it as a repo secret}"
: "${ANDROID_KEY_PASSWORD:?ANDROID_KEY_PASSWORD is not set — add it as a repo secret}"

android_dir="src-tauri/gen/android"
gradle="$android_dir/app/build.gradle.kts"
[ -f "$gradle" ] || { echo "::error::$gradle not found — run 'tauri android init' first"; exit 1; }

# 1. Materialize the keystore from the base64 secret (absolute path so Gradle resolves it
#    regardless of which module dir it evaluates from).
keystore_path="$(pwd)/$android_dir/release.jks"
echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > "$keystore_path"

# 2. keystore.properties at the Android project root (rootProject dir for Gradle).
cat > "$android_dir/keystore.properties" <<EOF
storeFile=$keystore_path
storePassword=$ANDROID_KEYSTORE_PASSWORD
keyAlias=$ANDROID_KEY_ALIAS
keyPassword=$ANDROID_KEY_PASSWORD
EOF

# 3. Teach the generated build.gradle.kts to load those properties and sign the release build.
#    The Tauri template ships a `buildTypes { ... getByName("release") { ... } }` block with no
#    signing — we splice a release signingConfig in front of buildTypes and wire it into the
#    release type. Anchors ("buildTypes {", 'getByName("release") {') are stable Tauri template text.
#    NB: in Gradle's Kotlin DSL, fully-qualified `java.util.Properties()` / `java.io.FileInputStream`
#    fail to resolve in expression position, so we add imports and use simple names. `getProperty()`
#    returns a platform `String!`, which assigns cleanly without an `as String` cast (the cast would
#    trip "no cast needed", which Gradle's strict script compilation treats as an error).
if grep -q 'signingConfigs.getByName("release")' "$gradle"; then
  echo "Signing config already present in $gradle — skipping injection."
else
  grep -q '^import java\.io\.FileInputStream' "$gradle" || perl -0777 -i -pe 's/\A/import java.io.FileInputStream\n/' "$gradle"
  grep -q '^import java\.util\.Properties' "$gradle" || perl -0777 -i -pe 's/\A/import java.util.Properties\n/' "$gradle"

  perl -0777 -i -pe 's/(\n(\s*)buildTypes\s*\{)/\n${2}val keystorePropertiesFile = rootProject.file("keystore.properties")\n${2}val keystoreProperties = Properties()\n${2}if (keystorePropertiesFile.exists()) {\n${2}    keystoreProperties.load(FileInputStream(keystorePropertiesFile))\n${2}}\n${2}signingConfigs {\n${2}    create("release") {\n${2}        keyAlias = keystoreProperties.getProperty("keyAlias")\n${2}        keyPassword = keystoreProperties.getProperty("keyPassword")\n${2}        storeFile = file(keystoreProperties.getProperty("storeFile"))\n${2}        storePassword = keystoreProperties.getProperty("storePassword")\n${2}    }\n${2}}\n$1/' "$gradle"

  perl -0777 -i -pe 's/(getByName\("release"\)\s*\{)/$1\n            signingConfig = signingConfigs.getByName("release")/' "$gradle"
fi

# 4. Fail loudly if either splice didn't land (e.g. the template moved).
grep -q 'create("release")' "$gradle" || { echo "::error::failed to inject signingConfigs into $gradle"; exit 1; }
grep -q 'signingConfig = signingConfigs.getByName("release")' "$gradle" || { echo "::error::failed to wire signingConfig into the release buildType in $gradle"; exit 1; }

echo "Android release signing configured."
